# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: firefly.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'firefly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfirefly.proto\"\x1d\n\x0cPhaseMessage\x12\r\n\x05phase\x18\x01 \x01(\x02\"\x1c\n\nAckMessage\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2Y\n\x07\x46irefly\x12\'\n\tSendPhase\x12\r.PhaseMessage\x1a\x0b.AckMessage\x12%\n\x0cRequestPhase\x12\x06.Empty\x1a\r.PhaseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firefly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHASEMESSAGE']._serialized_start=17
  _globals['_PHASEMESSAGE']._serialized_end=46
  _globals['_ACKMESSAGE']._serialized_start=48
  _globals['_ACKMESSAGE']._serialized_end=76
  _globals['_EMPTY']._serialized_start=78
  _globals['_EMPTY']._serialized_end=85
  _globals['_FIREFLY']._serialized_start=87
  _globals['_FIREFLY']._serialized_end=176
# @@protoc_insertion_point(module_scope)
