# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import firefly_pb2 as firefly__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in firefly_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FireflyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPhase = channel.unary_unary(
                '/Firefly/SendPhase',
                request_serializer=firefly__pb2.PhaseMessage.SerializeToString,
                response_deserializer=firefly__pb2.AckMessage.FromString,
                _registered_method=True)
        self.RequestPhase = channel.unary_unary(
                '/Firefly/RequestPhase',
                request_serializer=firefly__pb2.Empty.SerializeToString,
                response_deserializer=firefly__pb2.PhaseMessage.FromString,
                _registered_method=True)


class FireflyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPhase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPhase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FireflyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPhase,
                    request_deserializer=firefly__pb2.PhaseMessage.FromString,
                    response_serializer=firefly__pb2.AckMessage.SerializeToString,
            ),
            'RequestPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPhase,
                    request_deserializer=firefly__pb2.Empty.FromString,
                    response_serializer=firefly__pb2.PhaseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Firefly', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Firefly', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Firefly(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Firefly/SendPhase',
            firefly__pb2.PhaseMessage.SerializeToString,
            firefly__pb2.AckMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Firefly/RequestPhase',
            firefly__pb2.Empty.SerializeToString,
            firefly__pb2.PhaseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
